name: Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Clean env
        run: |
          cargo clean
          rm -rf target
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt clippy
      - name: Rustfmt
        run: cargo fmt --check
      - name: Cargo test
        run: cargo test --all-features
      - uses: taiki-e/install-action@cargo-hack
      - name: Cargo build
        run: |
          cargo hack check --each-feature --no-dev-deps
          cargo hack check --feature-powerset --no-dev-deps
      - name: Clippy
        run: cargo clippy
      - name: Benchmark builds
        run: cargo check --benches
      - name: Check example works
        run: |
          cd example/file_inference
          cargo run --release -- --file=./audios/sample_1.mp3
