name: Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt clippy

      - name: Rustfmt
        run: cargo fmt --check

      - name: Cargo test
        run: cargo test --all-features

      - uses: taiki-e/install-action@cargo-hack

      - name: Cargo build
        run: |
          cargo hack build --each-feature --no-dev-deps
          cargo hack build --feature-powerset --no-dev-deps


      - name: Clippy
        run: cargo clippy
